version: '3.7'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  redis_data: {}

services:
  memcached:
    image: memcached:1.5.16

  redis:
    image: redis:5.0.5-buster
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:10.9-alpine
    env_file: ./.docker-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    &django
    init: true
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - memcached
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  jupyter:
    <<: *django
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    command: jupyter_entrypoint.sh


  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A config worker -l INFO

  celerybeat:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    command: /start-flower
